### ISSUE TITLE
Bug: Invalid action required

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#103]
This happened

![image](https://cloud.githubusercontent.com/assets/1219256/16660499/8f6ad3b0-443c-11e6-932b-af623e8f995b.png)

**Comment by yamikuronue** [comment]
@AccaliaDeElementia I have no idea what's up with this, something about chats? Can you take a look?

**Comment by AccaliaDeElementia** [comment]
huh. that looks like an exception being thrown..... got a stack trace?

**Comment by yamikuronue** [comment]
Getting this for everything in chat

```
Yamikuronue less than a minute ago
!kill dreikin
 yamibot less than a minute ago
Error killing player: Error: [[invalid-argument:required]]

Tsaukpaetra less than a minute ago
!next-phase
 yamibot less than a minute ago
Error incrementing phase: Error: [[invalid-argument:required]]
```

I did get a stack though:

```
  sockbot:commands executing command "next-phase" +23s
  sockbot:mafia:modController Error: [[invalid-argument:required]]
    at Object.parseJSON (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/lib/utils.js:147:15)
    at new Topic (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/providers/nodebb/topic.js:38:29)
    at Function.parse (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/providers/nodebb/topic.js:366:20)
    at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/providers/nodebb/topic.js:354:40
    at process._tickCallback (node.js:369:9) +38s
```

**Comment by AccaliaDeElementia** [comment]
looks like this was related to #119?

**Comment by yamikuronue** [comment]
Working on this
