### ISSUE TITLE
Double chats?

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#147]
Postman mode created a chat, and the chat ID was 6858. Due to #144 it wasn't added to the game. So I added it.

Two aliases were added:

```
        "aliases": [
            "testmafia",
            "t_17966",
            "c_6858",
            "c_undefined"
        ]
```

I also get two bubbles popping up when a message is sent. Somehow it's being duplicated?

**Comment by yamikuronue** [comment]
Also received this:

```
  sockbot:mafia:modController Received add thread/chat request in testMafia from Yamikuronue +4m
  sockbot Error: [[error:invalid-data]]
    at Socket.continuation (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/providers/nodebb/index.js:416:31)
    at Socket.onack (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/node_modules/socket.io-client/lib/socket.js:305:9)
    at Socket.onpacket (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/node_modules/socket.io-client/lib/socket.js:229:12)
    at Manager.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/node_modules/socket.io-client/node_modules/component-emitter/index.js:131:20)
    at Manager.ondecoded (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/node_modules/socket.io-client/lib/manager.js:333:8)
```

**Comment by AccaliaDeElementia** [comment]
hmm... that stack trace is rather less helpful than i would have hoped for..... 

-sigh- 

i'll look into it, it's 100% reproduceable i assume?

**Comment by yamikuronue** [comment]
I think this has to do with renaming chats after sending, though we had trouble reproducing it manually.
