### ISSUE TITLE
Game lookup by name issue

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#98]
Yamibot stack trace during bug swarm:

```
sockbot TypeError: Cannot read property 'load' of undefined
    at getGameByName (/home/ubuntu/workspace/src/dao/index.js:125:20)
    at MafiaModController.listNAHandler (/home/ubuntu/workspace/src/mod_controller.js:395:23)
    at Command.execute (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/lib/commands.js:183:49)
    at exec (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/lib/commands.js:453:28)
    at Commands.execute (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/lib/commands.js:455:20)
    at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/providers/nodebb/notification.js:392:42
    at process._tickCallback (node.js:369:9) +1ms
```

**Comment by yamikuronue** [comment]
Same for id:

 sockbot:mafia:modController Listing night actions for 17966 +2m
  sockbot TypeError: Cannot read property 'load' of undefined
    at getGameByTopicId (/home/ubuntu/workspace/src/dao/index.js:109:20)
    at MafiaModController.listNAHandler (/home/ubuntu/workspace/src/mod_controller.js:395:23)
    at Command.execute (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/lib/commands.js:183:49)
    at exec (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/lib/commands.js:453:28)
    at Commands.execute (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/lib/commands.js:455:20)
    at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/sockbot/providers/nodebb/notification.js:392:42
    at process._tickCallback (node.js:369:9) +1ms

**Comment by AccaliaDeElementia** [comment]
ah. you accidentally unbound the context from the dao when you introduced lookupFunc.

try running 

`lookupFunc.call(this.dao, gameid)` instead of `lookupFunc(gameId)`

that should sort things out.
